name: Build image

on:
  schedule:
    - cron: '20 20 * * *'  # 8:20pm everyday
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ github.event.repository.name }}
  GITHUB_USERNAME: ${{ github.repository_owner }}
  GITHUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        major_version: [37]
        include:
          - major_version: 37
            is_latest: true
            is_stable: true

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log into Docker Hub registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Log into GitHub registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ env.GITHUB_USERNAME }}
          password: ${{ env.GITHUB_PASSWORD }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            docker.io/${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
            ghcr.io/${{ env.GITHUB_USERNAME }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=false
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=semver,pattern={{version}}
            type=match,pattern=.*,value=${{ matrix.major_version }}

      - name: Extract Docker stable tag
        if: matrix.is_stable == true
        id: meta_stable
        uses: docker/metadata-action@v4
        with:
          images: |
            docker.io/${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
            ghcr.io/${{ env.GITHUB_USERNAME }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=false
          tags: |
            type=match,pattern=.*,value=stable

      - name: Extract Docker latest tag
        if: matrix.is_latest == true
        id: meta_latest
        uses: docker/metadata-action@v4
        with:
          images: |
            docker.io/${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
            ghcr.io/${{ env.GITHUB_USERNAME }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=false
          tags: |
            type=match,pattern=.*,value=latest

      - name: Build Image
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: |
            ./Containerfile
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ steps.meta_stable.outputs.tags }}
            ${{ steps.meta_latest.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            FEDORA_MAJOR_VERSION=${{ matrix.major_version }}
          oci: true

      - name: Push to container registries
        uses: redhat-actions/push-to-registry@v2
        id: push
        with:
          tags: ${{ steps.build_image.outputs.tags }}
          extra-args: |
            --disable-content-trust

      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v3
        with:
          repository: ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
          short-description: ${{ github.event.repository.description }}

      - name: Echo outputs
        run: |
          echo "${{ toJSON(steps.push.outputs) }}"
